language: python

sudo: false

addons:
  apt:
    packages:
    - libffi-dev
    - libsasl2-dev
    - libldap2-dev

matrix:
  include:
    - python: 3.5.2
      env: TOXENV=py35 BUILD=code
    - python: 3.4.4
      env: TOXENV=py34 BUILD=code
    - python: 2.7
      env: TOXENV=py27 BUILD=code
    - python: 3.5.2
      env: TOXENV=py35 BUILD=docs


install:
  - |
    set -ex
    case "$BUILD" in
      code)
        pip install -U tox ;;
      docs)
        pip install -U sphinx ;;
    esac
    set +ex


script:
  - |
    set -ex
    case "$BUILD" in
      code)
        tox ;;
      docs)
        SPHINXOPTS=-W make html ;;
    esac
    set +ex
