language: python

sudo: false

addons:
  apt:
    packages:
    - libffi-dev
    - libsasl2-dev
    - libldap2-dev

matrix:
  include:
    - python: 3.5.2
      env: TOXENV=py35
    - python: 3.4.4
      env: TOXENV=py34
    - python: 2.7
      env: TOXENV=py27


install:
  - pip install -U tox

script:
  - tox
