language: python

sudo: false

addons:
  apt:
    packages:
    - libffi-dev
    - libsasl2-dev
    - libldap2-dev

env:
  - TOX_ENV=py27
  - TOX_ENV=py34

install:
  - pip install -U tox

script:
  - tox -e $TOX_ENV

