language: python
python:
  - 3.4.3 # specify 3.4.3, tox will still handle 2.7 ok

sudo: false

addons:
  apt:
    packages:
    - libffi-dev
    - libsasl2-dev
    - libldap2-dev

env:
  - TOXENV=py27
  - TOXENV=py34

install:
  - pip install -U tox

script:
  - tox